name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn

      - name: build and run e2e
        run: yarn e2e
        env:
          API_GITHUB_CLIENT_ID: ${{ secrets.API_GITHUB_CLIENT_ID }}
          API_GITHUB_CLIENT_SECRET: ${{ secrets.API_GITHUB_CLIENT_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker build/push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/site:latest
          platforms: linux/amd64,linux/arm/v7
          push: true

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker image
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd APP
            ./update_fe.sh
          host: calitb.dev
          user: pi
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
