name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: calitb/calitb.dev/site
          registry: docker.pkg.github.com
          username: 'calitb'
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: 'latest'
