name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn

      - name: linter
        run: yarn lint

      - name: Contentful Migration
        run: ./contentful/environment/setup.sh
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_TARGET_ENVIRONMENT: 'e2e'
          MANAGEMENT_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN }}

      - name: build and run tests
        run: |
          yarn test:coverage
          yarn test:coverage:report
        env:
          API_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.API_GITHUB_PERSONAL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ENVIRONMENT: 'e2e'

      - name: gets coverage
        if: github.ref == 'refs/heads/main'
        id: test_coverage
        run: |
          coverage=`sed -n 47p coverage/lcov-report/index.html | awk -F '>' '{print $2}' | awk -F '%' '{print $1}'`
          echo "::set-output name=COVERAGE::$coverage"
          if (( $(echo "$coverage <= 50" | bc -l) )) ; then
            echo "::set-output name=COLOR::red"
          elif (( $(echo "$coverage > 80" | bc -l) )); then
            echo "::set-output name=COLOR::success"
          else
            echo "::set-output name=COLOR::orange"
          fi

      - name: generate test coverage badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: calitbdev-test-coverage.json
          label: TestCoverage
          message: '${{steps.test_coverage.outputs.COVERAGE}}%'
          color: '${{steps.test_coverage.outputs.COLOR}}'
          cacheSeconds: 300

      - name: Production Build
        if: github.ref == 'refs/heads/main'
        run: yarn build
        env:
          API_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.API_GITHUB_PERSONAL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ENVIRONMENT: 'master'

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: generate .env.local file
        if: github.ref == 'refs/heads/main'
        run: |
          echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env.local
          echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env.local
          echo "CONTENTFUL_ENVIRONMENT=$CONTENTFUL_ENVIRONMENT" >> .env.local
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}

      - name: Docker build/push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/site:latest
          platforms: linux/amd64,linux/arm/v7
          push: true

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker image
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd APP
            ./update_fe.sh
          host: calitb.dev
          user: pi
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
