name: Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn

      - name: linter
        run: yarn lint

      - name: unit tests
        run: yarn test:ci

      - name: gets unit tests coverage
        if: github.ref == 'refs/heads/main'
        id: coverage
        run: |
          coverage=`sed -n 47p coverage/lcov-report/index.html | awk -F '>' '{print $2}' | awk -F '%' '{print $1}'`
          echo "::set-output name=COVERAGE::$coverage"
          if (( $(echo "$coverage <= 50" | bc -l) )) ; then
            echo "::set-output name=COLOR::red"
          elif (( $(echo "$coverage > 80" | bc -l) )); then
            echo "::set-output name=COLOR::success"
          else
            echo "::set-output name=COLOR::orange"
          fi

      - name: generate unit tests coverage badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: calitbdev-coverage.json
          label: coverage
          message: '${{steps.coverage.outputs.COVERAGE}}'
          color: '${{steps.coverage.outputs.COLOR}}'
          cacheSeconds: 300

      - name: build and run e2e
        run: |
          rm -r coverage
          yarn e2e
          yarn e2e:report
        env:
          API_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.API_GITHUB_PERSONAL_ACCESS_TOKEN }}

      - name: gets e2e coverage
        if: github.ref == 'refs/heads/main'
        id: e2e_coverage
        run: |
          coverage=`sed -n 47p coverage/lcov-report/index.html | awk -F '>' '{print $2}' | awk -F '%' '{print $1}'`
          echo "::set-output name=COVERAGE::$coverage"
          if (( $(echo "$coverage <= 50" | bc -l) )) ; then
            echo "::set-output name=COLOR::red"
          elif (( $(echo "$coverage > 80" | bc -l) )); then
            echo "::set-output name=COLOR::success"
          else
            echo "::set-output name=COLOR::orange"
          fi

      - name: generate e2e coverage badge
        if: github.ref == 'refs/heads/main'
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: calitbdev-e2e-coverage.json
          label: e2e-coverage
          message: '${{steps.e2e_coverage.outputs.COVERAGE}}'
          color: '${{steps.e2e_coverage.outputs.COLOR}}'
          cacheSeconds: 300

      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker build/push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository_owner }}/site:latest
          platforms: linux/amd64,linux/arm/v7
          push: true

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker image
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd APP
            ./update_fe.sh
          host: calitb.dev
          user: pi
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
