name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build/push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: docker.pkg.github.com/calitb/servernextjs/site:latest
          platforms: linux/amd64,linux/arm64
          push: true
